### PR TITLE
SPRT-104 change background image to banner and footer

### PR DESCRIPTION
**Pull request by facuzero**
problem with changes, apparently don't reflect the images in page

### CODE REVIEW

**Review by njrzr — APPROVED** [review]

**Comment by njrzr** [comment]
It' all good here, I don't see any issue.

**Review by eddymdz — COMMENTED** [review]
@facuzero these changes affects the version of tailwind (downgrade). Is that ok?

**Comment by facuzero** [comment]
@eddymdz i'm gonna update tailwind

**Review by njrzr — APPROVED** [review]

**Comment by njrzr** [comment]
@facuzero resolve the merge conflict, see if the deleted element is used.

**Pull request merged**
