### PR TITLE
SPRT-126: Implement the language switcher in the pukara.es website

### PR DESCRIPTION
**Pull request by gnaomi0**

### CODE REVIEW

**Review by eddymdz — CHANGES_REQUESTED** [review]
@gnaomi0 I have some considerations:

- The base url cannot change, because is part of the github pages configuration
- I don't understand why you are exposing new ports in docker-compose file for this implementation
- The implementation doesn't accomplish the task criterias (Ex.: the switcher must be a flag...)
- When I open locally (localhost:1333) , I got an error page doesn't exists. By default the page is in Spanish, so we don't need specify /es

**Comment by gnaomi0** [comment]
> @gnaomi0 I have some considerations:
> 
> * The base url cannot change, because is part of the github pages configuration
Okay. Sorry, I didn't know.

> * I don't understand why you are exposing new ports in docker-compose file for this implementation
If I don't expose other ports, I cant see the english and portuguese version. Now I changed the url again and if the ports 1314 and 1315 are not declared it returns an error. Is this okay?

> * The implementation doesn't accomplish the task criterias (Ex.: the switcher must be a flag...)
I'll make some changes.

> * When I open locally (localhost:1333) , I got an error page doesn't exists. By default the page is in Spanish, so we don't need specify /es
Okay.

**Comment by gnaomi0** [comment]
@eddymdz  check my last comments here and jira.

**Comment by gnaomi0** [comment]
@eddymdz let me know if we need some adjustments

**Review by eddymdz — APPROVED** [review]
@gnaomi0 looks good

**Pull request merged**
